#!/bin/bash

webDavWrapper="webdavwrapper"
confDir="etc"
distConfFile="webdav.conf-dist"

chmodCmd="/bin/chmod"
chownCmd="/bin/chown"
sedCmd="/bin/sed"


function die ()
{
	echo "reconfig error: $1" >&2
    	exit 1
}

if [ $1 != "install" ]; then
	# nothing to be done, exit
	exit 0
fi

# In order to change the user and group ID at runtime, the webdavwrapper
# needs to be run as root (set-user-ID and set-group-ID bit)
webDavWrapperPath="${VHOST_CGIBINDIR}/${webDavWrapper}"
if ! ${chownCmd} root:root ${webDavWrapperPath}; then
	die "Chown for ${webDavWrapperPath} failed"
fi

if ! ${chmodCmd} ug+s ${webDavWrapperPath}; then
	die "set-user-id and set-group-id on ${webDavWrapperPath} failed"
fi


# Set the correct path within the config file
distConfFilePath="${VHOST_ROOT}/${confDir}/${distConfFile}"
if ! ${sedCmd} -i -e "s|^\(\$INSTALL_BASE\)=.*|\1='${VHOST_ROOT}/';|" \
         ${distConfFilePath}
then
	die "Setting INSTALL_BASE path in ${distConfFilePath} failed"
fi


# Adding logout support
# see: http://webdavcgi.sourceforge.net/doc.html#logout
echo "\$HEADER = '<div class=\"header\">WebDAV CGI - Web interface: You are logged in as <span title="'.`id -a`.'">' .\$ENV{REMOTE_USER}.'</span> (<a href="/logout">Logout</a>).</div>';" >> ${distConfFilePath}
